<?php 

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_650c515fc2087',
		'title' => 'IRM Slider',
		'fields' => array(
			// image field, logo, return id
			array(
				'key' => 'field_650c515fc2088',
				'label' => 'Logo',
				'name' => 'logo',
				'aria-label' => '',
				'type' => 'image',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'uploader' => '',
				'acfe_thumbnail' => 0,
				'upload_folder' => '',
			),
			array(
				'key' => 'field_63ff1588c61d7',
				'label' => 'Slides',
				'name' => 'slider',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Row',
				'sub_fields' => array(
					array(
						'key' => 'field_63ff15aec61d8',
						'label' => 'Media',
						'name' => 'media',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'image' => 'image',
							'video' => 'video',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
						'allow_custom' => 0,
						'search_placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'parent_repeater' => 'field_63ff1588c61d7',
					),
					array(
						'key' => 'field_63ff15f2c61d9',
						'label' => 'Image',
						'name' => 'image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_63ff15aec61d8',
									'operator' => '==',
									'value' => 'image',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'uploader' => '',
						'acfe_thumbnail' => 0,
						'upload_folder' => '',
						'parent_repeater' => 'field_63ff1588c61d7',
					),
					array(
						'key' => 'field_63ff1a421f820',
						'label' => 'Image (mobile)',
						'name' => 'mobile_image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_63ff15aec61d8',
									'operator' => '==',
									'value' => 'image',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'uploader' => '',
						'acfe_thumbnail' => 0,
						'upload_folder' => '',
						'parent_repeater' => 'field_63ff1588c61d7',
					),
					array(
						'key' => 'field_63ff1619c61da',
						'label' => 'Video',
						'name' => 'video',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_63ff15aec61d8',
									'operator' => '==',
									'value' => 'video',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => 'mp4',
						'uploader' => '',
						'preview_style' => 'default',
						'placeholder' => 'Select',
						'upload_folder' => '',
						'button_label' => 'Add File',
						'stylised_button' => 0,
						'file_count' => 0,
						'multiple' => 0,
						'min' => '',
						'max' => '',
						'parent_repeater' => 'field_63ff1588c61d7',
					),
					array(
						'key' => 'field_63ff16a7438a3',
						'label' => 'Video (mobile)',
						'name' => 'mobile_video',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_63ff15aec61d8',
									'operator' => '==',
									'value' => 'video',
								),
							),
						),
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => 'mp4',
						'uploader' => '',
						'preview_style' => 'default',
						'placeholder' => 'Select',
						'upload_folder' => '',
						'button_label' => 'Add File',
						'stylised_button' => 0,
						'file_count' => 0,
						'multiple' => 0,
						'min' => '',
						'max' => '',
						'parent_repeater' => 'field_63ff1588c61d7',
					),
					array(
						'key' => 'field_63ff164ac61de',
						'label' => 'Content',
						'name' => 'content',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'acfe_wysiwyg_auto_init' => 0,
						'acfe_wysiwyg_height' => 300,
						'acfe_wysiwyg_min_height' => 300,
						'acfe_wysiwyg_max_height' => '',
						'acfe_wysiwyg_valid_elements' => '',
						'acfe_wysiwyg_custom_style' => '',
						'acfe_wysiwyg_disable_wp_style' => 0,
						'acfe_wysiwyg_autoresize' => 0,
						'acfe_wysiwyg_disable_resize' => 0,
						'acfe_wysiwyg_remove_path' => 0,
						'acfe_wysiwyg_menubar' => 0,
						'acfe_wysiwyg_transparent' => 0,
						'acfe_wysiwyg_merge_toolbar' => 0,
						'acfe_wysiwyg_custom_toolbar' => 0,
						'acfe_wysiwyg_toolbar_buttons' => array(
						),
						'parent_repeater' => 'field_63ff1588c61d7',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'irm-slider',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );
